language: python
python:
- '2.7'
- '3.4'

install: 
- pip install --upgrade pip
- pip install --upgrade -r requirements_dev.txt
- python setup.py sdist
- pip install dist/Tsidii-*.tar.gz

script: 
- py.test -v

